import './globals.css'

// import { Inter as Handwritten } from 'next/font/google'

import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
// import ThemeContext, { ThemeProvider } from '@/context/ThemeContext'
// import { useContext } from 'react'


export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

// const handwritten = Handwritten({
//   subsets: ['latin'],
//   variable: '--font-handwritten'
// });

// <style jsx global>
//   {`
//     :root {
//       --font-handwritten: ${handwritten.style.fontFamily}
//     }
//   `}
// </style>

export default function RootLayout({ children }) {
  // const { theme } = useContext(ThemeContext)
  return (

    <html >
      <body className='bg-zinc-50 text-white flex justify-center items-center dark:bg-black'>
        <div className='bg-white min-h-screen w-[100vw] border-x border-zinc-100 sm:w-[92vw] lg:w-[85vw] dark:bg-zinc-900 dark:border-zinc-700'>
          <div className='bg-white mx-8 sm:mx-10 md:mx-14 lg:mx-20 xl:mx-24  dark:bg-zinc-900'>
            <Navbar />
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html>

  )
}
